[tool.poetry]
name = "beancount-script"
version = "1.0.2"
description = "Scripts I use for my accounting using beancount"
authors = ["Mayeu <m@mayeu.me>"]
license = "AGPL-3.0-or-later"

packages = [
    { include = "bin/*" },
]

[tool.poetry.dependencies]
python = "^3.7"
beancount = "^2.2"
